### ISSUE TITLE
Defining an enumeration within a struct sometimes succeeds [14398]

### ISSUE THREAD

**Issue by JLBuenoLopez-eProsima** [eProsima/Fast-DDS-Gen#108]
[IDL specification](https://www.omg.org/spec/IDL/4.2/About-IDL/) does not allow the definition of enumerations within the structure declaration. Thus, the following IDL definition should fail:

```idl
struct Foo {

  enum Bar {
    a,
    b
  } bar;

};
```

Currently, Fast DDS-Gen generates the files without including enumerator variable `bar`, but it does not fail nor issues a warning to the user.

This bug has been found thanks to report #107.

**Comment by xiaokezhou** [comment]
THANK you for answer #107 quickly； Can you do me a favor to locate the rule your mentioned in OMG IDL datasheet? The  datasheet is huge, and my searching ability is poor ....

**Comment by JLBuenoLopez-eProsima** [comment]
You can directly look into the "Annex A: Consolidated IDL Grammar" where the grammar is defined. Both `<struct_dcl>` and `<enum_dcl>` are within the `<constr_type_dcl>`. If you look into the `<struct_dcl>` you will see that it is not allowed to define another `<constr_type_dcl>` within (nested structures are not allowed either, for instance).

**Comment by xiaokezhou** [comment]
> You can directly look into the "Annex A: Consolidated IDL Grammar" where the grammar is defined. Both `<struct_dcl>` and `<enum_dcl>` are within the `<constr_type_dcl>`. If you look into the `<struct_dcl>` you will see that it is not allowed to define another `<constr_type_dcl>` within (nested structures are not allowed either, for instance).

It looks clear! I will follow your guide. THANKS !!!!

**Comment by richiware** [comment]
I will close this issue because was answered. If any trouble, you can reopen it.
