### ISSUE TITLE
Fastddsgen example when supplied -typeros2 is not compatible with ROS2 topic names [14455]

### ISSUE THREAD

**Issue by RFRIEDM-Trimble** [eProsima/Fast-DDS-Gen#111]
As a user of fastddsgen, I can generate ROS2 compliant message headers from an IDL file, however if I build an example, I cannot subscribe or publish to the example application because it is missing prefixes.

I think the only thing is missing is to prefix the example publisher and subscriber with `rt/` if the `-typeros2` argument is supplied.

References:
https://design.ros2.org/articles/topic_and_service_names.html
https://answers.ros.org/question/319723/use-ros2-fastrtps-with-standalone-fastrtps-programs/
https://github.com/davidhodo/ros2_idl_demo
https://github.com/briancaglioni/FASTDDS_ROS2_Pub_Sub_Guide
https://github.com/eProsima/Fast-DDS-Gen/pull/22
https://docs.ros.org/en/foxy/Releases/Release-Galactic-Geochelone.html#ability-to-invoke-rosidl-pipeline-outside-cmake
https://github.com/eProsima/Integration-Service/issues/174

**Comment by RFRIEDM-Trimble** [comment]
I created a pull request here: https://github.com/eProsima/Fast-DDS-Gen/pull/112

This appears to work, however the participant does not show up in `ros2 node list`. I have yet to determine what is necessary to do that, however it doesn't prevent the data from being exchanged.

**Comment by JLBuenoLopez-eProsima** [comment]
Closing the ticket following the same reasoning as [this comment](https://github.com/eProsima/Fast-DDS-Gen/pull/112#issuecomment-1711529166)
