### ISSUE TITLE
Hoping IDL supports C++11 enum class

### ISSUE THREAD

**Issue by nanh1998** [eProsima/Fast-DDS-Gen#139]
Hello, I have some issues using IDL files. Current version only support enum in IDL, but I'd like to use C++ 11 enum class to solve some conflict problems in my project. Here's an example:
`enum Type1 {
    kUpdate/* = 0x00U */,
    kInstall/* = 0x01U */,
};

enum Type2 {
    KStart/* = 0x00U */,
    kUpdate/* = 0x01U */,
    kInstall/* = 0x02U */,
};

// This case may cause compile error: type not support
if value == kInstall

enum class Type1 {
    kUpdate/* = 0x00U */,
    kInstall/* = 0x01U */,
};
enum class Type2 {
    KStart/* = 0x00U */,
    kUpdate/* = 0x01U */,
    kInstall/* = 0x02U */,
};
// This case works perfect with enum class
if value == Type1::kInstall
if value == Type2::kInstall`

Hope you can add this feature in the future IDL versions, any help would be much appreciated.

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @nanh1998,

First of all, thank you very much for your suggestion! What you propose is included in the [OMG C++11 Language Mapping specification](http://www.omg.org/spec/CPP11/1.1/PDF/) section 6.9 "Mapping for Enums". But as you mention, Fast DDS-Gen does not support this specification yet. Also, [Fast DDS roadmap](https://github.com/eProsima/Fast-DDS/blob/master/roadmap.md) does not include the implementation of this specification in the short term. You may consider contacting our [commercial support team](https://github.com/eProsima/Fast-DDS#getting-help) for options to prioritize this enhancement.

**Comment by nanh1998** [comment]
Hi @JLBuenoLopez-eProsima,

Thanks a lot for you nice reply! I would contact the support team as you suggested :)
