### ISSUE TITLE
Wrong value generated for `is_plain` on certain cases [18160]

### ISSUE THREAD

**Issue by MiguelCompany** [eProsima/Fast-DDS-Gen#141]
The generated method `is_plain` is not taking into account the alignment padding of the compiler.

See eProsima/Fast-DDS#2777 for an example.

The solution would be to generate something similar to the following:

```
    eProsima_user_DllExport inline bool is_plain() const override
    {
        return offsetof(<type_name>, <last_field>) + sizeof(<last_field>) == <type_name>::getMaxCdrSerializedSize();
    }
```

**Comment by briansoe66** [comment]
@MiguelCompany , can you explain how to use the proposed is_plain() function to detect a misaligned message? I would like to check:
1. if I require padding in my message
2. if my padding was done correctly

**Comment by richiware** [comment]
eProsima/Fast-DDS-Gen#169 should fix this issue. Closing.
