### ISSUE TITLE
unable to build with openjdk version "17.0.5" 2022-10-18

### ISSUE THREAD

**Issue by persan** [eProsima/Fast-DDS-Gen#146]
Build fails with Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 61.
Sugested solution:
use gradle-7.6-bin.zip.

**Comment by JLBuenoLopez-eProsima** [comment]
Thanks for your report @persan 

Support for Java 17 was introduced in Gradle 7.3 as shown in [Gradle documentation](https://docs.gradle.org/current/userguide/compatibility.html#java). Currently, `gradlew` script is using Gradle 7.0. #147 updates the script to use the latest version as suggested.
