### ISSUE TITLE
multiple idl with same name is not supported

### ISSUE THREAD

**Issue by briansoe66** [eProsima/Fast-DDS-Gen#161]
fastddsgen folder1/foo.idl folder2/foo.idl generates header source for only one of the foo.idl. All files are written to the same output folder, without preserving the original subdirectory structure, so the files are probably be generated but then overwritten.

This issue would therefore be solve by fixing this issue: https://github.com/eProsima/Fast-DDS-Gen/issues/32

**Comment by JLBuenoLopez-eProsima** [comment]
@briansoe66 

The latest Fast DDS-Gen release, v3.0.0, preserves the subdirectory structure. Could you check again and if confirmed could you please consider closing this issue?
