### ISSUE TITLE
Build Error when executing the command `gradle assemble` with Gradle version 8.0.2

### ISSUE THREAD

**Issue by leo0807** [eProsima/Fast-DDS-Gen#162]
Is there an already existing issue for this?
I have searched the existing issues

Hi! I'm currently working on the installation of `Fast-DDS-Gen` on my `MacOS`; however, the installation failed as I met the below errors. How could I solve this issue?

This is the `URL` of official website: `https://fast-dds.docs.eprosima.com/en/latest/installation/sources/sources_mac.html`

Here is the instructions from the official website:
```
brew install gradle

cd ~
git clone --recursive https://github.com/eProsima/Fast-DDS-Gen.git
cd Fast-DDS-Gen
gradle assemble
```

when I executed the command `gradle assemble`, I met the following error:

```
> Task :buildIDLParser FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/scott/Fast-DDS-Gen/thirdparty/idl-parser/build.gradle' line: 79

* What went wrong:
A problem occurred evaluating project ':idl-parser'.
> Could not set unknown property 'classifier' for task ':idl-parser:sourceJar' of type org.gradle.api.tasks.bundling.Jar.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
2 actionable tasks: 2 executed

``` 

Here is my `gradle` info:
```
------------------------------------------------------------
Gradle 8.0.2
------------------------------------------------------------

Build time:   2023-03-03 16:41:37 UTC
Revision:     7d6581558e226a580d91d399f7dfb9e3095c2b1d

Kotlin:       1.8.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          19.0.2 (Homebrew 19.0.2)
OS:           Mac OS X 12.3.1 x86_64


```

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @leo0807 

Fast DDS-Gen does not support Gradle 8 which was released last month. Just recently, Fast DDS-Gen started supporting Gradle 7 that introduces support for newer Java versions (#129). Please, use a supported Gradle version or just use the `gradlew` script provided in the repository to build Fast DDS-Gen.

**Comment by leo0807** [comment]
Thanks for your response, I got it.
