### ISSUE TITLE
Modules create invalid header guard

### ISSUE THREAD

**Issue by burak-yildizoz** [eProsima/Fast-DDS-Gen#167]
As requested by issue eProsima/Fast-DDS#195, the generated C++ code honors the module name in the header guard.
However, the technique used to convert lowercase to uppercase must be locale-free.
For instance, if the module name is `invalid`, the generated header guard becomes `İNVALİD` in Turkish locale.
`toUpperCase` method in commit [`f058a03`](https://github.com/eProsima/Fast-DDS/commit/f058a036d51357b3419e72312ff48834df82af5f) should be replaced with `std::toupper`.
Another issue is that if there are nested modules, the header guard uses the innermost module name of the last struct.
It would be better if it uses the outermost module name.

**Comment by gozdekirbiz** [comment]
I'm having the same issue. Any planned updates for this problem?

**Comment by JesusPoderoso** [comment]
Hi, Fast DDS Gen in `master` branch uses [java string `toUpperCase()` method](https://www.w3schools.com/java/ref_string_touppercase.asp) in [the guard generation](https://github.com/eProsima/Fast-DDS-Gen/blob/dd8aa30535681b8de113599989756c38e203dd51/src/main/java/com/eprosima/fastdds/idl/grammar/Context.java#L590).
We are not planning to change it in shot-middle terms. 
Maybe running the Fast DDS Gen from a docker with the desired Locale suits your needs.
