### ISSUE TITLE
fastddsgen -python can't find template module.st

### ISSUE THREAD

**Issue by michaelchao** [eProsima/Fast-DDS-Gen#182]
I cloned newest branch code and compile source code successfully.
Using command
```shell
fastddsgen -python middle.image.idl
```
but got an error
```shell
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
Loading templates...
Processing the file middle.image.idl...
ERROR<Exception>: Can't find template module.st; group hierarchy is [FastCdrCommon]
Exception in thread "main" java.lang.NullPointerException
        at com.eprosima.fastdds.fastddsgen.execute(fastddsgen.java:407)
        at com.eprosima.fastdds.fastddsgen.main(fastddsgen.java:1481)
```

**middle.image.idl** content:
```c++
module dds {
struct MiddleImage {
  long Depth;
  string Name;
};
};
```

However, when I change idl content to 
```c++
// module dds {

struct MiddleImage {
  long Depth;
  string Name;

};

// };
```

command executed ok.

Can't i use **module** keyword in idl?

**Comment by JLBuenoLopez-eProsima** [comment]
There is already another open issue regarding this topic: #88. Also, there is currently some work being done to fix it. You can found it in [this branch](https://github.com/eProsima/Fast-DDS-Gen/tree/feature/python-modules). You may try and see if it fixes the issue. Nevertheless, I am going to close this, to keep the discussion unified in the original ticket.
