### ISSUE TITLE
Version 2.5.1 still show version 2.3 with fastddsgen -version 

### ISSUE THREAD

**Issue by kenjiWuJian** [eProsima/Fast-DDS-Gen#210]
Steps to reproduce:
1. Download zip file from Release 2.5.1 https://github.com/eProsima/Fast-DDS-Gen/releases/tag/v2.5.1
2. unzip and enter scripts folder
3. type fastddsgen -version 

The result is :
sgen -version
openjdk version "11.0.20" 2023-07-18
OpenJDK Runtime Environment (build 11.0.20+8-post-Ubuntu-1ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.20+8-post-Ubuntu-1ubuntu120.04, mixed mode, sharing)
fastddsgen version 2.3.0

Why v2.5.1 shows version 2.3.0?
Is it only a wrong message? 
How to get the correct latest version?

**Comment by EduPonz** [comment]
Hi @kenjiWuJian,

I'm afraid the ZIP files in the release are put there by GitHub and are not the proper way to install Fast DDS Gen. The following commands are the proper way to achieve what you want:

```bash
git clone -b v2.5.1 https://github.com/eProsima/Fast-DDS-Gen.git
cd Fast-DDS-Gen/
./gradlew assemble
./scripts/fastddsgen -version
```

This for me outputs:

```
openjdk version "17.0.8" 2023-07-18
OpenJDK Runtime Environment (build 17.0.8+7-Ubuntu-122.04)
OpenJDK 64-Bit Server VM (build 17.0.8+7-Ubuntu-122.04, mixed mode, sharing)
fastddsgen version 2.5.1

```

I'm closing this issue for now. Please feel free to reopen should the above not work for you.
