### ISSUE TITLE
Warning for deprecated features in Gradle [13722]

### ISSUE THREAD

**Issue by TSC21** [eProsima/Fast-DDS-Gen#28]
Using Gradle 6.2, I get the following warning when using `assemble` or `build`:
```sh
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings
```
Using `--warning-mode all` indicates what are the deprecated features. I did some changes on `build.gradle` and could easily fix some of those, but there are also a lot in the **IDL-Parse**.

It might be reasonable to fix those eventually.

**Comment by LuisGP** [comment]
You can use a system Gradle, but **Fast-RTPS-Gen** and **IDL-Parser** come with an embedded gradle wrapper. To use it, you must use the `gradlew` (or `gradlew.bat`) script.

Best regards.

**Comment by TSC21** [comment]
> You can use a system Gradle, but **Fast-RTPS-Gen** and **IDL-Parser** come with an embedded gradle wrapper. To use it, you must use the `gradlew` (or `gradlew.bat`) script.
> 
> Best regards.

I understand. But why not make it compatible with the system Gradle? Well not compatible, but at least make sure we sync both versions. I mean having a wrapper is good, but having an updated wrapper is better.

**Comment by JLBuenoLopez-eProsima** [comment]
#129 has just been merged updating to the latest gradle version and removing the deprecation notices. I will proceed and close the issue.
