### ISSUE TITLE
fastrtpsgen: Create/keep directory structure to be equivalent to rtiddsgen? [6239]

### ISSUE THREAD

**Issue by codewithpassion** [eProsima/Fast-DDS-Gen#32]
Hey,

We have a few IDL files in a folder structure representing their namespace structure. 
A simplified example:
common/Header.idl
common/Time.idl
system/TestMessage.idl
devices/ImuMessage.idl

Now, TestMessage and ImuMessage reference the Header and Time types. 
I'm passing the right `-I` arguments so that fastrtpsgen can find the IDL files. 

Using the RTI Connext generator tool, what I get is a directory structure:
common/Header.[h|cxx]
common/Time.[h|cxx]
system/TestMessage.[h|cxx}
devices/ImuMessage.[h|cxx]

But **fastrtpsgen** is creating the common types inside both the  system  and devices folder.
That means, I get multiple definitions for **Header** and **Type**.

Is there a way to keep the directory structure and get the common types only generated once?

Is this possible without  code change?

Regards,
Dom

**Comment by webhoppery** [comment]
Maybe use the C preprocessor to 'inline' the IDL #include statements before running fastddsgen.

The Test.zip file has a :
	msg_Include dir - has IDLs with #include
	msg_Inlined dir - where the IDL #include have been preprocessed

The two CMakeLists*.txt files are from when using #include and when the 'top level' IDLs are preprocessed to inline the #include statements.
	CMakeLists-orov-sensor-Include.txt
		add_library and add_executable for every IDL processed
	CMakeLists-orov-sensor-Inlined.txt
		Only add_library and add_executable for the TopicIDLs

=====================
Procedure :
If the IDL that defines the Topic data has #include statements,  preprocess those IDLs. 

> CL /P /C *.idl	Outputs *.i files.  On Win10 with VS2022 CL :

Tidy up the *.i files ( Remove "#line" lines )
Copy *.i to *.idl

Delete or rename (to *.idd) the IDLs included with #include so fastddsgen doesn't process them. If the included IDL is also used as the 'top level' Topic data IDL, don't delete or rename it.

Then run fastddsgen in each directory.
[Test.zip](https://github.com/eProsima/Fast-DDS-Gen/files/8026922/Test.zip)

It sure made my life easier processing Dom's Trident IDLs with Fast-DDS.

What's the right terminology / lingo for the IDL that defines the entire Topic data? TopicIDL? TL_IDL? Lvl-1_IDL?

**Comment by briansoe66** [comment]
[This PR ](https://github.com/eProsima/Fast-CDR/pull/139) adds a cmake function (fastddsgen.cmake), that will run fastddsgen, and move the header/source so that the directory structure is equivalent to rtiddsgen

**Comment by JLBuenoLopez-eProsima** [comment]
Latest Fast DDS-release, v3.0.0, keeps the folder structure when generating the type support code.
