### ISSUE TITLE
Can I convert UMAA IDL files to code using Fast-DDS-Gen?(Windows or Linux)

### ISSUE THREAD

**Issue by Jay-Ppark** [eProsima/Fast-DDS-Gen#356]
Can I convert UMAA IDL files to code using Fast-DDS-Gen?(Windows or Linux)
Is there a way?

**Comment by JesusPoderoso** [comment]
Hi @Jay-Ppark,
as long as those IDL files follow [the Fast DDS Gen supported types](https://fast-dds.docs.eprosima.com/en/latest/fastddsgen/dataTypes/dataTypes.html#supported-idl-types), you can generate C++ or python code.
