### ISSUE TITLE
Cannot generate java binding code

### ISSUE THREAD

**Issue by huangjie84** [eProsima/Fast-DDS-Gen#370]
`-replace -example CMake    -flat-output-dir  -d idl\ -language java    D:\workspace-sim\Fast-DDS-Gen\idl\sonsor.idl`
when I user these params to generate for java code.there is a lot of errors, did this program support for java?

**Comment by huangjie84** [comment]
the .idl file content is 

```
module SensorDataModule {
    struct TemperatureReading {
        string location;
        double degreesCelsius;
    };

    struct HumidityReading {
        string location;
        double percentHumidity;
    };
    struct PressureReading {
        string location;
        double millibars;
    };

};
```

**Comment by JesusPoderoso** [comment]
Closing in favor of
https://github.com/eProsima/Fast-DDS/discussions/5022
