### ISSUE TITLE
is_plain_xcdrv1_impl() and is_plain_xcdrv2_impl() are identical in generated code

### ISSUE THREAD

**Issue by zoeeer** [eProsima/Fast-DDS-Gen#390]
When a type is declared with `@final` extensibility, the generated code has two versions for `is_plain()` method, but they seem identical.

see: https://github.com/eProsima/Fast-DDS/commit/4c9f1d6ff2bd6ef4ab79327809c0e74f3db74238#r146264299

![image](https://github.com/user-attachments/assets/2e6bb585-8114-4cc1-adeb-383f68806b7d)

The type is defined as such:

```
@extensibility(FINAL)
struct DeliveryMechanisms
{
	unsigned long index;
	char message[32];
};
```

**Comment by Mario-DL** [comment]
Hi @zoeeer,

Yes, the same output will be produced for `plain` and `final` for serialization mechanisms except if using `unsigned long long` or `unsigned double`. 
Feeling free to close this as it is not an issue.

**Comment by zoeeer** [comment]
oh, thanks for the explanation.
