### ISSUE TITLE
Issue with sequence<T_Char> not being sent when it reaches length 101...

### ISSUE THREAD

**Issue by ross-newman** [eProsima/Fast-DDS-Gen#43]
We are trying to implement strings as sequence<T_Char> and have issues with the DataWriter returning false and not seeing the message being recieved by the subscriber.

To demonstrate the issue we created a test IDL file:
```
typedef char T_Char;
typedef sequence<T_Char> T_Payload;
struct I_Kit_Logging {
  T_Payload A_payload;
};
```

Using this IDL we generated an example application using fastrtpsgen -example (v.1.0.4). We then added the code to encode strings and decode (on subscriber). The resulting example is on Github (https://github.com/ross-newman/fastdds-vector-limit). 

The Publisher always retunrs false (https://github.com/ross-newman/fastdds-vector-limit/blob/master/testPublisher.cxx Line 110) when the number of chars reaches 101. This seems to be a limit? Is there a QoS setting we need to modify? Have reviewed the defaults but cant not find a setting that would limit the size of the vector?

**Comment by LuisGP** [comment]
Hi @ross-newman 

By default, Fast-DDS uses [PREALLOCATED](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/core/policy/eprosimaExtensions.html#memorymanagementpolicy) history memory profile QoS. By default, an unbounded sequence using preallocation defines its maximum size to 100, because a maximum size is needed in preallocated mode.
To make it work with unbounded sequences larger than 100 elements, the memory policy must be changed to any other value, for example, `DYNAMIC_REUSABLE_MEMORY_MODE`.

**Comment by ross-newman** [comment]
Do I apply this QoS on both publisher and subscriber? Also can I set this once for all readers/writers? i.e.
```
RTPSEndpointQos endpoint;
//The RTPSEndpointQos is default constructed with history_memory_policy = PREALLOCATED
//Change the history_memory_policy to DYNAMIC_RESERVE
endpoint.history_memory_policy = eprosima::fastrtps::rtps::DYNAMIC_RESERVE_MEMORY_MODE;
```
One instance of RTPSEndpointQos for all writers? No extra code needed to apply the OoS setting? Call once on application startup.

**Comment by LuisGP** [comment]
Hi @ross-newman 

Yes, you must apply the QoS on both endpoints.
To set it once for all readers/writers you must modify the default [DataWriterQos](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/publisher/dataWriter/dataWriter.html?highlight=RTPSEndpointQos#default-datawriterqos)/[DataReaderQos](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/subscriber/dataReader/dataReader.html#default-datareaderqos) in the publisher/subscriber.
You can do it by using a default [XML Profile](https://fast-dds.docs.eprosima.com/en/latest/fastdds/xml_configuration/xml_configuration.html) too.

Each endpoint copies its own Qos on the creation and once it is enabled, the Qos cannot be modified.

**Comment by ross-newman** [comment]
Great that worked, thanks.
