### ISSUE TITLE
fastrtpsgen: no viable alternative at input 'struct Object'

### ISSUE THREAD

**Issue by fschoenm** [eProsima/Fast-DDS-Gen#44]
fastrtpsgen seems unable to handle calling a struct _Object_. Renaming the struct to something else e.g. _Object1_ works.

I have the following IDL file:

	module pk_msgs {
	    module msg {
	        struct Object {
	            int64 id;
	        };
	    };
	};

Trying to generate code for this IDL file shows the following error:

	openjdk version "1.8.0_265"
	OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~20.04-b01)
	OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
	Loading templates...
	Processing the file obj.idl...
	obj.idl:3:15: error: no viable alternative at input 'struct Object'
	obj.idl:7:0: error: Unexpected input '}'
	Exception in thread "main" java.lang.NullPointerException
	        at com.eprosima.fastrtps.fastrtpsgen.execute(fastrtpsgen.java:343)
	        at com.eprosima.fastrtps.fastrtpsgen.main(fastrtpsgen.java:1207)

fastrtpsgen is version 1.0.4.

	openjdk version "1.8.0_265"
	OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~20.04-b01)
	OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
	fastrtpsgen version 1.0.4

## Steps to Reproduce

1. Use the IDL file above.
2. Call ``fastrtpsgen -d output obj.idl``
3. Observe error.
4. Rename _Object_ to something else, e.g. _Object1_ and repeat the steps without error.

## System information

- Fast-RTPS version: n/a
- OS: Ubuntu 20.04.1
- Network interfaces: n/a
- ROS2: n/a

**Comment by jwillemsen** [comment]
Object is a reserved keyword in IDL (see section of 7.2.4 of https://www.omg.org/spec/IDL/4.2/PDF). Have you tried `_Object` (the prefix underscore is the normal way to escape IDL keywords)

**Comment by jwillemsen** [comment]
Be aware that `int64` is a IDL4 extension which is not supported yet by all DDS vendors, using `long long` will result in the same generated code but is portable

**Comment by jwillemsen** [comment]
Ok, your first proposal is legal IDL. I would recommend not to use anonymous types, so make your definition

```
module pk_msgs {
    module msg {
      typedef sequence<pk_msgs::msg::_Object> ObjectSeq;
        @topic
        struct Objects {
          std_msgs::msg::Header header;
          ObjectSeq objs;
        };
    };
};
```

**Comment by fschoenm** [comment]
@jwillemsen Thanks for the suggestion. I will try it tomorrow.

**Comment by jwillemsen** [comment]
I have tried with ridl (see https://github.com/RemedyIT/ridl), which you could easily install and use through our AXCIOMA bootstrap repo (see https://github.com/RemedyIT/axcioma)

**Comment by fschoenm** [comment]
> 
> 
> Ok, your first proposal is legal IDL. I would recommend not to use anonymous types, so make your definition
> 
> ```
> module pk_msgs {
>     module msg {
>         typedef sequence<pk_msgs::msg::_Object> ObjectSeq;
>         @topic
>         struct Objects {
>           std_msgs::msg::Header header;
>           ObjectSeq objs;
>         };
>     };
> };
> ```

This also does not work.

Here's a minimal example that shows the problem (even without any includes):

        module pk_msgs {
                module msg {
                        struct _Object {
                                int64 id;
                        };

                        typedef sequence<_Object> ObjectSeq;

                        struct Objects {
                                ObjectSeq objs;
                        };
                };
        };

It produces the following error:

	openjdk version "1.8.0_265"
	OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~20.04-b01)
	OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
	        Loading templates...
	        Processing the file obj.idl...
	        obj.idl:7:19: error: '_Object' was not defined previously
	        obj.idl:10:3: error: 'ObjectSeq' was not defined previously
	Exception in thread "main" java.lang.NullPointerException
	        at com.eprosima.fastrtps.fastrtpsgen.execute(fastrtpsgen.java:343)
	        at com.eprosima.fastrtps.fastrtpsgen.main(fastrtpsgen.java:1207)

**Comment by jwillemsen** [comment]
This works with ridl and tao_idl so looks you have encountered a bug in fastrtpsgen

**Comment by fschoenm** [comment]
> This works with ridl and tao_idl so looks you have encountered a bug in fastrtpsgen

Well, that's why I opened the ticket here in the first place.

**Comment by jwillemsen** [comment]
Looks this issue has to be moved to https://github.com/eProsima/IDL-Parser

**Comment by JLBuenoLopez-eProsima** [comment]
This issue has been closed in the corresponding repository and several releases have been made. I will close this ticket but feel free to reopen if it is still not completely solved or open a new one if you find any other issue.
