### ISSUE TITLE
Support for the @value annotation for the "enum" type

### ISSUE THREAD

**Issue by i-and** [eProsima/Fast-DDS-Gen#45]
Can you support code generation of enumeration value assignments using the standard @value annotation?

**Comment by zip-link** [comment]
Have you solved this problem. I use the gen program of version 2.0.0 and use @ value to specify the default value of enum, but the actual value is 0, 1, 2 and 3;

**Comment by zip-link** [comment]
Have you solved this problem. I use the gen program of version 2.0.0 and use @ value to specify the default value of enum, but the actual value is 0, 1, 2 and 3;

enum Enumeration
{	
	@value(10) RED,
	GREEN,
        BLUE
};
