### ISSUE TITLE
Generated VS project doesn't seem to be linking deps corrently [13728]

### ISSUE THREAD

**Issue by ghostravenstorm** [eProsima/Fast-DDS-Gen#48]
UPDATE:
So, using the gen tool to build a x64Win64VS2015 project doesn't seem to build right a project with corrently linked libraries, but generating a CMake project does corrently link libraries and those projects build successfully. 
Something is clearly up with the Windows flags on the generator.

Oen more thing: running the example project built with the gen tool that created a cmake project that was built doesn't run correctly. It runs into an issue with shared libraries. I guess I don't have something installed correctly, or the program is looking in places different from the install instructions.
```
Ghost@DESKTOP-G1T94C6 MINGW64 ~/Workspace/Nike-Cpp/build/Debug
$ ./Nike.exe subscriber
C:/Users/Ghost/Workspace/Nike-Cpp/build/Debug/Nike.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

UPDATE:
I have it working now with the CMake generated project. I just added all the fastdds, fastcdr, and foonathan stuff to environment varaibles, and that solved the issue with missing shared libraries. I thought the FASTDSHOME variable would have been enough, but apparently not.

=========================================================

I generated a simple IDL and used the gen tool to make a VS 2015 project.
I have foonathan_memory_vendor, fastdds, and fastcdr corrently installed on my system.
I also have env vars corrently set to these dirs, but the VS compiler cannot find header files.

```
/// Nike.idl
struct Messenger {
   string msg;
}
```

Output from building project generated by Fast-DDS-Gen
```
1>------ Build started: Project: NikeTypes, Configuration: Debug DLL x64 ------
1>  Nike.cxx
1>h:\storage\vcom3d\amm\projects\_compatibilitytestingworkspace\fastddscpp01\nike.cxx(28): fatal error C1083: Cannot open include file: 'fastcdr/Cdr.h': No such file or directory
2>------ Build started: Project: NikePublisherSubscriber, Configuration: Debug DLL x64 ------
2>  NikeSubscriber.cxx
2>h:\storage\vcom3d\amm\projects\_compatibilitytestingworkspace\fastddscpp01\nikesubscriber.cxx(22): fatal error C1083: Cannot open include file: 'fastdds/dds/domain/DomainParticipantFactory.hpp': No such file or directory
2>  NikePublisher.cxx
2>h:\storage\vcom3d\amm\projects\_compatibilitytestingworkspace\fastddscpp01\nikepublisher.h(26): fatal error C1083: Cannot open include file: 'fastdds/dds/domain/DomainParticipant.hpp': No such file or directory
2>  NikePubSubTypes.cxx
2>h:\storage\vcom3d\amm\projects\_compatibilitytestingworkspace\fastddscpp01\nikepubsubtypes.cxx(23): fatal error C1083: Cannot open include file: 'fastcdr/FastBuffer.h': No such file or directory
2>  NikePubSubMain.cxx
2>h:\storage\vcom3d\amm\projects\_compatibilitytestingworkspace\fastddscpp01\nikepublisher.h(26): fatal error C1083: Cannot open include file: 'fastdds/dds/domain/DomainParticipant.hpp': No such file or directory
2>  Generating Code...
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========
```

Dependenceis installed
![image](https://user-images.githubusercontent.com/14009559/101065312-fea18f00-3562-11eb-95eb-21fe2e610dcf.png)

Environment vars
![image](https://user-images.githubusercontent.com/14009559/101065293-f77a8100-3562-11eb-8e66-f8915609b4c6.png)

VS linker input
![image](https://user-images.githubusercontent.com/14009559/101065447-2bee3d00-3563-11eb-9c89-f82d26a3a8da.png)

**Comment by ghostravenstorm** [comment]
So not having `FASTRTPSHOME` as an env var pointing to `\'Program Files (x86)'\fastrtps` is part of the problem. Still missing FastCDR includes.

I fail to see where

**Comment by ghostravenstorm** [comment]
Doesn't seem to work even when you manually add the include dir
![image](https://user-images.githubusercontent.com/14009559/101094289-28ba7780-358a-11eb-9251-c18a8807e036.png)

**Comment by ghostravenstorm** [comment]
Works when you manually add the include dir for fastcdr. Now need to do the same for libfastcdrd-1.0.lib.
Shouldn't the gen tool have already done this?
![image](https://user-images.githubusercontent.com/14009559/101094648-bbf3ad00-358a-11eb-88a7-4495ce9c1a9e.png)

**Comment by ghostravenstorm** [comment]
The linker is now complaining about not being able to find a `libfastcdrd-1.0.lib`, but the FastDDSGen tool did make one for me. It made a `fastcdrd-1.0.lib` though.
![image](https://user-images.githubusercontent.com/14009559/101095357-cd898480-358b-11eb-9121-74dfac3b13e9.png)

**Comment by ghostravenstorm** [comment]
I changed the name and am now getting these errors.
```
1>------ Build started: Project: NikeTypes, Configuration: Debug DLL x64 ------
1>  Nike.cxx
1>     Creating library .\lib\x64Win64VS2015\NikeTypesd.lib and object .\lib\x64Win64VS2015\NikeTypesd.exp
1>Nike.obj : error LNK2019: unresolved external symbol "public: class eprosima::fastcdr::Cdr & __cdecl eprosima::fastcdr::Cdr::serialize(char const *)" (?serialize@Cdr@fastcdr@eprosima@@QEAAAEAV123@PEBD@Z) referenced in function "public: class eprosima::fastcdr::Cdr & __cdecl eprosima::fastcdr::Cdr::serialize(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?serialize@Cdr@fastcdr@eprosima@@QEAAAEAV123@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
1>Nike.obj : error LNK2019: unresolved external symbol "private: char const * __cdecl eprosima::fastcdr::Cdr::readString(unsigned int &)" (?readString@Cdr@fastcdr@eprosima@@AEAAPEBDAEAI@Z) referenced in function "public: class eprosima::fastcdr::Cdr & __cdecl eprosima::fastcdr::Cdr::deserialize(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)" (?deserialize@Cdr@fastcdr@eprosima@@QEAAAEAV123@AEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
1>C:\Program Files (x86)\fastcdr\lib\libfastcdrd-1.0.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64'
1>C:\Users\Ghost\Workspace\nike_cpp\bin\x64Win64VS2015\NikeTypesd.dll : fatal error LNK1120: 2 unresolved externals
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

The one standing out to me is teh machine type and target type. This is a x64 machine I'm compiling on. Why does it say this? I generated a x64 project from the gen tool. 

Are the FastCDR libs x86 only?

FYI I'm trying to only build the Types project at the moment.
![image](https://user-images.githubusercontent.com/14009559/101096603-c5cadf80-358d-11eb-9189-284f9dccb606.png)

**Comment by ghostravenstorm** [comment]
I just built everything on Linux following the guides and instructions for Linux using the same IDL, and I had no problems. 
Doing this for Windows currently doesn't work.

**Comment by JLBuenoLopez-eProsima** [comment]
@ghostravenstorm 

Just recently we have checked that the Windows examples are correctly generated and built. Can you please check using Fast DDS-Gen v3.0.0. Also, VS2015 is not an officially supported platform so consider upgrading to a more recent VS version (VS19 is the Tier 1 Windows supported platform).
