### ISSUE TITLE
Preprocessor error when fastddsgen.bat run on IDL

### ISSUE THREAD

**Issue by gmihi** [eProsima/Fast-DDS-Gen#59]
I used FastDDS windows installer exe VS2017 x64 to install FastDDS on my windows-10 PC
after installation completed 

I tried to generate DDS support files as below using fastddsgen.bat and cmake
I am using the workplace as example folder in the installation directory

Inside FastDDSGenHelloWorld1 I have HelloWorld.idl file and the CMakeLists.txt

C:\Program Files\eProsima\fastrtps 2.3.0\examples\C++\DDS\FastDDSGenHelloWorld1>fastddsgen.bat -example CMake HelloWorld.idl
Loading templates...
Processing the file HelloWorld.idl...
ERROR<callPreprocessor>: Cannot execute the preprocessor. Reason: Cannot run program "cl.exe": CreateProcess error=2, The system cannot find the file specified
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.eprosima.fastdds.solution.Project.getIDLIncludeFiles()" because "project" is null
        at com.eprosima.fastdds.fastddsgen.execute(fastddsgen.java:343)
        at com.eprosima.fastdds.fastddsgen.main(fastddsgen.java:1207)

**Comment by MiguelCompany** [comment]
@gmihi You can do several things here:

1. Running `fastddsgen` from a VS command prompt. This way the preprocessor will be on the path.
2. You can pass the path to the preprocessor using argument `-ppPath` when invoking `fastddsgen`
3. As you are building `HelloWorld.idl`, which does not require the preprocessor (as it has no `#include`), you could use argument `-ppDisable` when invoking `fastddsgen`

**Comment by gmihi** [comment]
MiguelCompany thanks, it works as you have explained ...

**Comment by wanfenglinhai** [comment]
thank you very much ,the problem has been solved！
