### ISSUE TITLE
DDS XTypes and @optional [13735]

### ISSUE THREAD

**Issue by goehle** [eProsima/Fast-DDS-Gen#63]
Hi,

I’m looking to use FastDDS to write some microservices and need to utilize the @optional IDL annotation and the corresponding optional functionality described in DDS XTypes (e.g., 7.2.1.3, 7.4.1, 7.4.1.2, 7.5.1.2.4.2 of DDX-XTypes v 1.3).  As far as I can tell, based on documentation [here](https://fast-dds.docs.eprosima.com/en/latest/fastddsgen/dataTypes/dataTypes.html?highlight=%40optional#annotations) and my own experiments, FastDDS version 2.3 does not support this functionality.  Is this there a plan to add @optional in a future release?  If so, is there an estimated timeline? 

Thanks. 

Geoff Goehle

**Comment by GregoryEAllen** [comment]
https://github.com/eProsima/xtypes/issues/82 My impression is that FastDDS currently can't speak XTypes, with or without the `@optional` keyword.

**Comment by JLBuenoLopez-eProsima** [comment]
Fast DDS-Gen v3.0.0 introduces support for `@optional` annotation. Other XTypes features are still being introduced/refactored.
