### ISSUE TITLE
fastddsgen can not handle nested module [13737]

### ISSUE THREAD

**Issue by yooouxin** [eProsima/Fast-DDS-Gen#68]
I find that fastddsgen will report error when have three nested modules(maybe another reason?)

For example,idl like this works well:

```idl
module dds{
    module interface{
        const int32 some_val = 0x1;
    };
};
```

But add one module would leading error:

```idl
module dds {
    module interface {
        module test {
            const int32 some_val = 0x1;
        };
    };
};
```

I want to know how to solve this problem,thank you!

**Comment by MiguelCompany** [comment]
@yooouxin I've checked with the last version of Fast DDS Gen, and both IDLs fail for the same reason: `interface` is a reserved IDL keyword. You can workaround this by using an underscore before the offending name.

The following IDL:
```IDL
module dds {
    module _interface {
        module test {
            const int32 some_val = 0x1;
        };
    };
};
```

Generates the following code:
```
namespace dds {
    namespace interface {
        namespace test {
            const int32_t some_val = 0x1;
        } // namespace test
    } // namespace interface
} // namespace dds
```

**Comment by JLBuenoLopez-eProsima** [comment]
I am going to close this issue because it has been answered already.
