### ISSUE TITLE
version string in build.gradle inconsistent with tags [13739]

### ISSUE THREAD

**Issue by kistlin** [eProsima/Fast-DDS-Gen#77]
The currently released version 2.0.2 prints 2.0.1, when executing `fastddsgen -version`.

Could this in the future be somehow linked to tags or checked during a build?

This could lead to confusion when the version string does not match the released version.

**Comment by kistlin** [comment]
and release v2.1.0 prints due to [4276ff4cea470c685109a5b03d1a7fdc8706b635](https://github.com/eProsima/Fast-DDS-Gen/commit/4276ff4cea470c685109a5b03d1a7fdc8706b635)
```
$ fastddsgen -version
fastddsgen version 2.1.1
```

**Comment by JLBuenoLopez-eProsima** [comment]
Closing this issue as it cannot be fixed after doing the release.
