### ISSUE TITLE
Maps should support non-primitive types [13386]

### ISSUE THREAD

**Issue by JLBuenoLopez-eProsima** [eProsima/Fast-DDS-Gen#83]
when i try following idl file:
```c++
struct nest
{
    double y;
    double x;
};

struct AsyncCommand
{
    string app_id;
    string command;
    map<string, double> parameters;
    map<string, nest> parameters1;
};
```
i get the error:
```
ERROR<Exception>: no such attribute: typeCodeMapElement in template context [struct_type if(ctx.anyCdr)_subtemplate anonymous if(!member.annotationNonSerialized)_subtemplate max_serialized_size elseif(typecode.isMapType)_subtemplate map_max_serialized_size map_max_serialized_size_element]
```

_Originally posted by @hehenihao in https://github.com/eProsima/Fast-DDS-Gen/issues/50#issuecomment-1003257954_

**Comment by JLBuenoLopez-eProsima** [comment]
@hehenihao,

I have opened a new issue with your comment as it is a different problem. Right now maps only support [primitive types](https://fast-dds.docs.eprosima.com/en/latest/fastddsgen/dataTypes/dataTypes.html#primitive-types). I am going to issue a PR in our [documentation](https://fast-dds.docs.eprosima.com/en/latest/fastddsgen/dataTypes/dataTypes.html#maps) to add a note stating this fact.

We will include this bugfix in our roadmap and we are going to leave this issue open until it is supported. Thanks for your contribution!

**Comment by JLBuenoLopez-eProsima** [comment]
Check eProsima/Fast-DDS-docs#316 for the clarification note included until the issue is solved.

**Comment by EduPonz** [comment]
Hi @hehenihao,

I've merged eProsima/Fast-DDS-docs#316. You can see the clarification [here](https://fast-dds.docs.eprosima.com/en/latest/fastddsgen/dataTypes/dataTypes.html#maps).

**Comment by hehenihao** [comment]
@EduPonz @JLBuenoLopez-eProsima 
Thanks for your update.

**Comment by JLBuenoLopez-eProsima** [comment]
@hehenihao 

Fast DDS latest release, v3.0.0, fixes this issue. Could you please check and, if confirmed, close the issue? Thanks!
