### ISSUE TITLE
Installation Fast-RTPS-Gen [13584]

### ISSUE THREAD

**Issue by ErickTurro** [eProsima/Fast-DDS-Gen#87]
Following this guideline https://dev.px4.io/master/en/setup/fast-rtps-installation.html, when I execute `sudo gradle install`, I get the following error:

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/home/droneuser/Fast-RTPS-Gen/build.gradle' line: 23

* What went wrong:
Could not compile build file '/home/droneuser/Fast-RTPS-Gen/build.gradle'.
> startup failed:
  build file '/home/droneuser/Fast-RTPS-Gen/build.gradle': 23: unable to resolve class org.gradle.api.tasks.options.Option
   @ line 23, column 1.
     import org.gradle.api.tasks.options.Option;
     ^
  
  1 error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by JLBuenoLopez-eProsima** [comment]
#129 has just been merged and this issue should be solved. Please reopen if after updating the issue is still happening.
