### ISSUE TITLE
fastddsgen -python option can't find template module.st [13638]

### ISSUE THREAD

**Issue by JLBuenoLopez-eProsima** [eProsima/Fast-DDS-Gen#88]
Every time I use the fastddsgen -python option I get the following error :

ERROR<Exception>: Can't find template module.st; group hierarchy is [FastCdrCommon]
Exception in thread "main" java.lang.NullPointerException
        at com.eprosima.fastdds.fastddsgen.execute(fastddsgen.java:401)
        at com.eprosima.fastdds.fastddsgen.main(fastddsgen.java:1474)

I didn't see the module.st anywhere in the eProsima Fast DDS v2.5.0 installation.

I get the same error on both Ubuntu v20.04.3 and Win10 21H2 on same dual boot laptop. Both with Fast DDS v2.5.0.

Fastddsgen works fine on both installations without the -python option.

_Originally posted by @webhoppery in https://github.com/eProsima/Fast-DDS/discussions/2444_

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @webhoppery,

Can you provide us with your IDL file? We would like to reproduce your issue at our end. We think it could be related to the use of namespaces in your IDL files but we want to check. Thanks for your contribution!

**Comment by webhoppery** [comment]
Hi,

Duration.idl (*.txt) shows issue.

[Duration.txt](https://github.com/eProsima/Fast-DDS-Gen/files/7959244/Duration.txt)

Command I used :
fastddsgen -replace -python -example CMake Duration.idl

**Comment by EduPonz** [comment]
Hi @webhoppery ,

Unfortunately, as stated [here](https://fast-dds.docs.eprosima.com/en/latest/fastddsgen/usage/usage.html#supported-options), `-python` and `-example` options are not yet compatible. That is, `-python` option can be used to generated python modules for your types, but Fast DDS-Gen cannot generate a python example just yet.

**Comment by webhoppery** [comment]
Hi Eduardo,

Checked on Ubuntu v20.0.4 :

$ fastddsgen -python Duration.idl
ERROR<Exception>: Can't find template module.st; group hierarchy is [FastCdrCommon]

I'd be curious about the python modules for the types, but this is nothing I need now, so I can wait and see what shows up in v2.5.1.

Thanks,
Bill

**Comment by JLBuenoLopez-eProsima** [comment]
Hi Bill,

We have just confirmed that your issue is related with the use of Modules in your IDL file. Right now it is not supported yet with the Python option. We take note to fix it. Thanks for your contribution!

**Comment by fabrizioschiano** [comment]
@JLBuenoLopez-eProsima I am also interested in this. Is there any news regarding this aspect?

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @fabrizioschiano

Thanks for reaching out. This is not currently in the developers team roadmap. If you are interested in moving this development forward, you may consider contacting our [commercial support team](https://github.com/eProsima/Fast-DDS#getting-help) for possible options.

**Comment by JLBuenoLopez-eProsima** [comment]
There is a potential fix for this issue in [this branch](https://github.com/eProsima/Fast-DDS-Gen/tree/feature/python-modules).

**Comment by richiware** [comment]
PR #194 (already in master branch) introduces modules in python code. I will close this issue. If any trouble, you can reopen it.
