### ISSUE TITLE
Generating from ros2 .msg file format [13830]

### ISSUE THREAD

**Issue by Nir-Az** [eProsima/Fast-DDS-Gen#92]
Hi,

I wish to generate code from a ros2 .msg file using `fastddsgen`.

1. When I try to input the .msg file (that only has 1 line inside "string name") and execute `fastddsgen` I gen a syntax error.
2. If I create an `idl` file using OMG syntax for it it works, but using the -typeros2 flag doesn't change anything, the output files stay the same with/without it.
I expected to see something different,  shouldn't I?

Thanks
Nir

**Comment by RFRIEDM-Trimble** [comment]
In [ROS2 galactic release notes,](https://docs.ros.org/en/foxy/Releases/Release-Galactic-Geochelone.html#ability-to-invoke-rosidl-pipeline-outside-cmake) they add a note about this. 

Testing this out, here's what I did. 

Create the message file
```
mkdir -p demo/msg
cd demo
cat << EOF > msg/Demo.msg
std_msgs/Header header
geometry_msgs/Twist twist
geometry_msgs/Accel accel
EOF
```
Run the generator
```
rosidl generate -o gen -t c -t cpp -t py -I$(ros2 pkg prefix --share std_msgs)/..   -I$(ros2 pkg prefix --share geometry_msgs)/.. demo msg/Demo.msg
```
View the idl file in the tmp directory
```
cat gen/cpp/tmp/msg/Demo.idl 
// generated from rosidl_adapter/resource/msg.idl.em
// with input from demo/msg/Demo.msg
// generated code does not contain a copyright notice

#include "geometry_msgs/msg/Accel.idl"
#include "geometry_msgs/msg/Twist.idl"
#include "std_msgs/msg/Header.idl"

module demo {
  module msg {
    struct Demo {
      std_msgs::msg::Header header;

      geometry_msgs::msg::Twist twist;

      geometry_msgs::msg::Accel accel;
    };
  };
};
```

Note:  You can see the includes looking for IDL files at the above paths; I am not yet sure how add `/opt/ros/galactic/share` to the IDL include path if you wanted to run fastddsgen. 
```
find /opt/ros/galactic/ | grep Twist.idl
/opt/ros/galactic/share/geometry_msgs/msg/Twist.idl
```

**Comment by JLBuenoLopez-eProsima** [comment]
Fast DDS-Gen is a tool independent from ROS 2 and it supports generation of Fast DDS TypeSupports from the OMG defined IDL format. I am afraid that it is not planned to support ROS 2 .msg format nor the `-typeros2` option is intended for the described use in this ticket. I think that ROS 2 has a tool to transform from .msg to IDL files.
