### ISSUE TITLE
Nested Structs sometimes not generating if included [13963]

### ISSUE THREAD

**Issue by methylDragon** [eProsima/Fast-DDS-Gen#97]
I am facing an issue where I am trying to generate source files for nested structures when IDL files are included.

Take for instance this IDL definition:
```
struct Vector3 { 
    double x; 
    double y; 
    double z; 
}; 
 
struct Accel { 
    Vector3 linear; 
    Vector3 angular; 
}; 
```
This generates as expected, but the moment you split it into two files it fails:

```
struct Vector3 { 
    double x; 
    double y; 
    double z; 
}; 
```

```
#include "Vector3.idl"

struct Accel { 
    Vector3 linear; 
    Vector3 angular; 
}; 
```

For some reason, invoking `fastddsgen` on 2.1.1. or 2.0.1. to generate Accel results in source files being generated that are practically empty, and the included file **Vector3.idl** does NOT generate. (Manually generating Vector3.idl first before invoking fastddsgen on Accel allows Vector3's sources to generate, but also results in the same empty Accel sources and headers):
```
#ifndef _FAST_DDS_GENERATED_ACCEL_H_
#define _FAST_DDS_GENERATED_ACCEL_H_


#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(Accel_SOURCE)
#define Accel_DllAPI __declspec( dllexport )
#else
#define Accel_DllAPI __declspec( dllimport )
#endif // Accel_SOURCE
#else
#define Accel_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define Accel_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima



#endif // _FAST_DDS_GENERATED_ACCEL_H_
```

In the tmp directory, this is the preprocessed input:
```
# 1 "./geometry_msgs/msg/Accel.idl"
# 1 "<built-in>"
# 1 "<command-line>"
# 31 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 32 "<command-line>" 2
# 1 "./geometry_msgs/msg/Accel.idl"
# 1 "./geometry_msgs/msg/Vector3.idl" 1
# 19 "./geometry_msgs/msg/Vector3.idl"
struct Vector3 {
    double x;
    double y;
    double z;
}
# 2 "./geometry_msgs/msg/Accel.idl" 2

struct Accel {
    Vector3 linear;
    Vector3 angular;
};
```

However, if a particular IDL definition has nested structs in a deep enough level, the lowest level struct seems to generate.
In a more practical example of this:
```
#ifndef __geometry_msgs__msg__AccelWithCovarianceStamped__idl 
#define __geometry_msgs__msg__AccelWithCovarianceStamped__idl 
 
#include "AccelWithCovariance.idl" 
#include "std_msgs/msg/Header.idl" 
 
module geometry_msgs { module msg { 
 
struct AccelWithCovarianceStamped { 
    std_msgs::msg::Header header; 
    geometry_msgs::msg::AccelWithCovariance accel; 
}; 
 
}; };  // module msg::geometry_msgs 
 
#endif  // __geometry_msgs__msg__AccelWithCovarianceStamped__idl 
```

Here, accel resolves to an AccelWithCovariance object, which stores an Accel object. And here, the Accel struct's definition generates as expected. However, **the AccelWithCovariance and AccelWithCovarianceStamped** structs DO NOT generate.

I'm not sure what is causing nested structs to refuse to be generating, and I'm also not sure why increasing the depth of nesting allows the deepest levels to generate...

**Comment by methylDragon** [comment]
If it helps, here's the preprocessor output for the two toy example versions listed above.

This one works:
```
# 1 "./geometry_msgs/msg/Accel.idl"
# 1 "<built-in>"
# 1 "<command-line>"
# 31 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 32 "<command-line>" 2
# 1 "./geometry_msgs/msg/Accel.idl"
struct Vector3 {
    double x;
    double y;
    double z;
};

struct Accel {
    Vector3 linear;
    Vector3 angular;
};
```

But once there is an include, it fails. This is the preprocessor output for the failing version:
```
# 1 "./geometry_msgs/msg/Accel.idl"
# 1 "<built-in>"
# 1 "<command-line>"
# 31 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 32 "<command-line>" 2
# 1 "./geometry_msgs/msg/Accel.idl"
# 1 "./geometry_msgs/msg/Vector3.idl" 1
# 19 "./geometry_msgs/msg/Vector3.idl"
struct Vector3 {
    double x;
    double y;
    double z;
};
# 2 "./geometry_msgs/msg/Accel.idl" 2

struct Accel {
    Vector3 linear;
    Vector3 angular;
};
```

**Comment by NeilTruter** [comment]
I am having the same problem.
Using fastddsgen version 2.0.1 the generated code is correct, using the latest version I experience the issue above, this happens using the exact same idl files for both versions of fastddsgen.

**Comment by tarichuo** [comment]
same problem with fastddsgen v2.1.3.

**Comment by tarichuo** [comment]
Found a solution, try to use absolute IDL file path instead of relative path。
Example：
`fastddsgen -cs -typeros2 -I /opt/ros/foxy/share -replace ./Header.idl  `   failed
`fastddsgen -cs -typeros2 -I /opt/ros/foxy/share -replace Header.idl`  worked
`fastddsgen -cs -typeros2 -I /opt/ros/foxy/share -replace /home/hjy/test/idl/Header.idl`  also worked

**Comment by JLBuenoLopez-eProsima** [comment]
@methylDragon 

Could you please check with Fast DDS-Gen latest release? Fast DDS-Gen CI tests the types defined in the [following repository](https://github.com/eProsima/dds-types-test) and the use case reported in this issue is included in those IDL files. Could you please check and if confirmed, close the issue? Thanks!

**Comment by methylDragon** [comment]
danke!
